\documentclass[fleqn,12pt]{article}

\topmargin=-0.3in
\textheight=8in
\oddsidemargin=0in
\textwidth=6.5in

\usepackage{amsthm,pifont}

\usepackage {tikz}
\usetikzlibrary {positioning}
\usetikzlibrary{trees,shapes,snakes}
\definecolor {processblue}{cmyk}{0.96,0,0,0}
\definecolor {ourcerulean}{RGB}{189,222,217}

\renewcommand\qedsymbol{\ding{120}}
\def\var{\ensuremath{\mbox{\rm var}}}
\def\cov{\ensuremath{\mbox{\rm cov}}}

\usepackage{indentfirst}

\setlength{\parindent}{0.6cm}

\newcommand{\refn}[1]{\raisebox{1ex}{\footnotesize{#1}}}

\newcounter{exno}

\begin{document}

\newpage

\setcounter{page}{1}
\renewcommand{\baselinestretch}{1.4142} \small\normalsize
\section*{Mathematical Modeling of Infectious Diseases, UCSF}

Version 2.0---modified 11 Mar 2017

\section*{Multistrain dynamics}
Let's return to the SIS model.  Just for familiarity, let's denote
the number of susceptibles by $X$.  
Let's imagine now that we have two strains of a pathogen, and 
that one ($Y$) is drug-susceptible or drug-sensitive, and the other ($W$)
is drug resistant.  We'll assume you can have only one at a time, and
that you can't get infected by one while you are infected by the other.

\begin{center}
\begin {tikzpicture}[-latex,auto,node distance=3 cm and 4cm,on grid,semithick,state/.style={circle,top color=white,bottom color=ourcerulean,draw,processblue,text=black,minimum width=1 cm}]
\node[state] (X) {$X$};
\node[state] (Y) [above right=of X] {$Y$};
\node[state] (W) [below right=of X] {$W$};
\path (X) edge [bend left = 30] node[below =0.15 cm] {$\beta \frac{Y}{N}$} (Y);
\path (Y) edge [bend right = -30] node[below =0.15 cm] {$\quad\quad\quad \quad\gamma + \theta (1-r)$} (X);
\path (X) edge [bend left = 30] node[below =0.15 cm] {$\beta \frac{W}{N}$} (W);
\path (W) edge [bend right = -30] node[below =0.15 cm] {$\gamma$} (X);
\path (Y) edge [bend right = -40] node[below =0.25 cm] {$\theta r \quad\quad$} (W);
\end{tikzpicture}
\end{center}

In this model, $X$ is the number of susceptible individuals, $Y$ the number of individuals
infected with the drug sensitive (same thing as drug susceptible) strain, and $W$ the number
infected with the drug resistant strain.  

We assume the force of infection for each strain is
proportional to the prevalence fraction for that strain, but we do not have to have the
same proportionality constant.  So let's say the force of infection for the
sensitive strain is $\beta_Y \frac{Y}{N}$ and for the resistant strain is $\beta_W \frac{W}{N}$.
For pencil and paper convenience we might write $\beta_Y = \beta$ and $\beta_W=b$.  It is 
natural to assume that $\beta_Y \geq \beta_W$, which says the wild type drug sensitive strain
is more transmissible.  If the resistant strain were more transmissible and thus more ``fit'', why
wasn't it the wild type to begin with?  But this sort of argument has limits and is not at
all to be taken as equivalent to empirical fact; we discussed examples from the influenza
literature of an oseltamivir-resistant flu strain that was believed more transmissible than
wild type.  But here we will assume a fitness cost of resistance, manifested as $\beta_W \leq \beta_Y$.
Let's emphasize the idea that drug resistant strains are assumed directly transmissible, capable of
independent circulation, and causing infections which are drug resistant right from the very
beginning.  This of course is known to happen in many diseases, including tuberculosis for
example.

We won't assume faster recovery from the resistant strain, though we could.  Instead we will
assume the same natural history, both recovering at rate $\gamma$.

In this model we introduce a new process, treatment.  For simplicity we are taking it to
be an independent occurrence from recovery.  Thus, as we saw under the competing risk example, the
total event rate is $\gamma + \theta$.  
{\bf Exercise \theexno.}\stepcounter{exno} Create refinement of this model such that treatment is less likely
near the start of infectiousness than later on.  There is no unique right answer; just draw the system diagram
or write the equations (no need to analyze).
\ding{122} \vskip 6pt

We're also going to assume that treatment might sometimes fail, causing drug resistant infection.  In other
words, a person, during the same bout of disease/infection could start out with the sensitive strain, try to 
get treated, fail treatment and then, without recovering, have a drug resistant infection.  We assume this
happens with probability $r$ per treatment.  So with rate $\theta$ you get treated, and conditional on being
treated, you actually are cured with probability $1-r$ and you fail with probability $r$ (leading to drug resistance).

We assume if you are drug resistant, you cannot be treated.  Of course in reality there might be other treatments, or
second line antibiotics, and so on.  And also, even if you fail with resistance, you might still benefit by reducing the
bacillary load and then recover at a higher rate.  The interplay of host immunity and pathogen population dynamics could be
much more complex in general.

Let's pause a moment to think about the issue of being cured in this model.  We have an exponential waiting time to
treatment, followed by a Bernoulli trial (whether it succeeds or fails).  We are assuming treatment with rate $\theta$.
The number of sensitive infectives is just $Y$, and in some tiny time period $\Delta t$, the number treated is
the number times the probability of treatment.  The probability of treatment is $\theta \Delta t$, so we have the
number $Y \theta \Delta t$.  The actual number leaving $Y$ in $\Delta t$ is $Y \theta$, so this is the flow rate out of
$Y$ due to treatment.  A fraction $r$ of these move down to $W$, and the others move back to $X$.  The equations are
\[
\frac{dX}{dt} = -\beta_Y \frac{Y}{N} X - \beta_W \frac{W}{N} X + \gamma Y + \gamma W + \theta (1-r) Y
\]
\[
\frac{dY}{dt} = \beta_Y \frac{Y}{N} X - \gamma Y - \theta Y
\]
\[
\frac{dW}{dt} = \beta_W \frac{W}{N} X -\gamma W + \theta r Y
\]
Add up all the equations, and you get 
\[
\frac{dX}{dt} + \frac{dY}{dt} + \frac{dW}{dt} = \frac{dN}{dt} = 0 ,
\]
with $N=X+Y+W$ being the total.  So the total doesn't change, by assumption.

The state of the population is defined by three numbers, $X$, $Y$, and $W$.  These form a dot moving around
in a three dimensional {\it phase space}, according to our equations.  But since

Let's go over the classical analysis of this model and see how it works.  First thing we might do is just look at
the prevalence fractions, since it turns out to be a little simpler.  For convenience, let's write the prevalence
fraction of drug susceptible infection as $y=Y/N$ and of drug resistant infection as $w=W/N$.  We'll write the
susceptible fraction as $x=X/N$, and we know $x+y+w=1$.  So 
\[
\frac{dy}{dt} = \frac{d}{dt} \frac{Y}{N} = \frac{1}{N}\frac{dY}{dt}
\]
and similarly for $dw/dt$, since $N$ is constant.

So we get
\[
\frac{dy}{dt} = \beta_Y y x - (\gamma + \theta) y
\]
and
\[
\frac{dw}{dt} = \beta_W w x - \gamma w + \theta r y
\]

We can just write $x=1-y-w$ and get
\[
\frac{dy}{dt} = \beta_Y y (1-y-w) - (\gamma + \theta) y
\]
and
\[
\frac{dw}{dt} = \beta_W w (1-y-w) - \gamma w + \theta r y
\]

So really, we can fully describe the motion as being in two dimensions, with a point $(y,w)$ moving around.  Once we know
those two numbers, we always know $x$ (the susceptible fraction).  Not only that, the point $(y,w)$ is always in a triangle
defined by $y \geq 0$, $w \geq 0$, and $y+w \leq 1$.

One thing right off the bat: if $y=0$, $\frac{dy}{dt}=0$.  If there aren't any drug sensitive infectives, there never will be; if
this variable is zero, then $y$ stays 0.  This doesn't tell us anything about $w$.  In fact let's look at the conditions
when $dy/dt=0$:
\[
\frac{dy}{dt}=0=y\big(\beta_Y (1-y-w) - (\gamma + \theta)\big)
\]
That second factor $\beta_Y (1-y-w)-(\gamma+\theta)$ could vanish too, and if it did, then $dy/dt$ would also equal zero.

This is also as good a time as any to
talk about nondimensionalization.  That's a big and interesting subject we can't do justice to here.  

I'm going to
pick a new time variable that has {\it no dimensions}.  Specifically, let 
\[
\tau = (\gamma + \theta) t .
\]
There are other choices.  But now, since $t$ has dimensions of time and $\gamma + \theta$ of reciprocal time, the new
$\tau$ is dimensionless, and $d\tau=(\gamma+\theta)\/dt$.
Now, if I have any variable, like $y$, 
\[
\frac{dy}{d\tau} = \frac{1}{\gamma+\theta}\frac{dy}{dt}.
\]
So in the new nondimensional form,
\[
\frac{dy}{d\tau} = \frac{\beta_Y}{\gamma+\theta} y (1-y-w) - y
\]
\[
\frac{dw}{d\tau} = \frac{\beta_W}{\gamma+\theta} w (1-y-w) - \frac{\gamma}{\gamma+\theta} w + \frac{\theta r}{\gamma+\theta} y
\]
That's not an instantly obvious blessing, but we do have the equations now written in dimensionless parameters.  It will
look nicer if we do a bit of renaming.  
\[
R_{YY} = \frac{\beta_Y}{\gamma+\theta}
\]
I'll tell you why this name in a moment.  I also want to name $\gamma/(\gamma+\theta)$; interpretively, it is the chance you
recover before treatment.  Let's call it 
\[
g = \frac{\gamma}{\gamma+\theta} .
\]
Using these new names, I could put
\[
\frac{\beta_W}{\gamma+\theta} = \frac{\beta_W}{\gamma} \frac{\gamma}{\gamma+\theta} .
\]
Then, let
\[
R_{WW} = \frac{\beta_W}{\gamma} .
\]
I haven't shown you why these names, and not some others, are helpful.  But no harm is done if you stick with me for
a moment---all you need is to see that I haven't actually done anything but convert time to a dimensionless quantity, and
rename the constants.

Now, the equations are
\[
\frac{dy}{d\tau} = R_{YY} y (1-y-w) - y
\]
\[
\frac{dw}{d\tau} = R_{WW} g w (1-y-w) - g w + (1-g)r y
\]

So---back to where we were.
Let's plot all the points where $dy/dt=0$.  To do so, let's pick some values.  Now, let's pick $R_{YY}=3$, $R_{WW}=2$, 
$g=2/3$, and $r=1/3$.  We have not analyzed the system, and we don't know if these are going to have ``typical'' behavior, or
be misleadingly special in some way.  It's OK to work out numerical features for a bunch of randomly chosen parameters to help
build your intuition on a new system as long as you are thoughtful about it.  (Try to falsify your conjectures numerically
before trying to prove something that isn't true!)

Look back at the equation $y(R_{YY}(1-y-w)-1)=0$, which is where $dy/d\tau=0$.  Assume we're looking at the second term
and $y>0$.  We have $1-y-w = 1/R_{YY}$, which is
\[
w=1-y-1/R_{YY} .
\]
This is a straight line with slope minus one, and vertical intercept $1-\frac{1}{R_{YY}}$.  

<<>>=
plot(0:1,0:1,type="n",xlab="y",ylab="w")
polygon(c(0,0,1,1),c(0,1,1,0),density=NA,col="black")
polygon(c(0,0,1),c(0,1,0),density=NA,col="white")
polygon(c(0,0,1,1),c(0,1,1,0),density=NULL,border="black")
abline(v=0,col="red",lwd=sqrt(2))
ryy <- 3
rww <- 2
g <- 2/3
r <- 1/3
yz.x <- seq(0,1,by=1/512)
wz.y <- 1-1/ryy - yz.x
points(yz.x,wz.y,type="l",col="red",lwd=sqrt(2))
@

In the plot, the black area is outside the permissible region; there is no meaning to $(y,w)$ points out there.
ON those red lines, $y$ is not changing.  There can't be any horizontal
motion of the $(y,w)$ point that represents the population.  

Now, what about the other equation?
\[
\frac{dw}{d\tau} = R_{WW} g w (1-y-w) - g w + (1-g)r y
\]
This seems a little less friendly, and the simpler way to deal with this looks like solving for $y$ in terms of $w$
actually:
\[
R_{WW}g w - R_{WW} g w y - R_{WW} g w^2 - g w + (1-g) r y = 0
\]
\[
R_{WW}g w - R_{WW} g w^2 - g w = R_{WW} g w y - (1-g)r y
\]
So
\[
y(R_{WW} g w  - (1-g)r)  = R_{WW}g w - R_{WW} g w^2 - g w 
\]
\[
y  = \frac{gw\big(R_{WW}(1-w)-1\big)}{R_{WW}g w - (1-g) r}
\]

Let's plot this.  (Note in the R code we have to be a little careful, so it doesn't try to join the two
sides of the hyperbola.)
<<>>=
plot(0:1,0:1,type="n",xlab="y",ylab="w")
polygon(c(0,0,1,1),c(0,1,1,0),density=NA,col="black")
polygon(c(0,0,1),c(0,1,0),density=NA,col="white")
polygon(c(0,0,1,1),c(0,1,1,0),density=NULL,border="black")
abline(v=0,col="red",lwd=sqrt(2))
yz.x.red <- seq(0,1,by=1/512)
wz.y.red <- 1-1/ryy - yz.x.red
points(yz.x.red,wz.y.red,type="l",col="red",lwd=sqrt(2))
wz.y.blue <- seq(0,1,by=1/512)
num <- wz.y.blue*g*(rww*(1-wz.y.blue) - 1)
den <- rww*g*wz.y.blue-(1-g)*r
dpos <- den>0
num1 <- num[dpos]
den1 <- den[dpos]
num2 <- num[!dpos]
den2 <- den[!dpos]
w1 <- wz.y.blue[dpos]
w2 <- wz.y.blue[!dpos]
w <- c(w1,NA,w2)
y <- c(num1/den1,NA,num2/den2)
points(y[y<1],w[y<1],type="l",col="blue",lwd=sqrt(2))
polygon(c(0,1,1),c(1,1,0),density=NA,col="black")
points(c(0,0),c(0,1/2))
@
Now I added the blue curve.  On the blue curve, $dw/d\tau=0$ and for an instant at least $w$ isn't changing.  If $w$ isn't
changing, then there isn't any vertical motion.  

Where blue and red touch, there is neither vertical nor horizontal motion---neither variable is changing and the system is
at equilibrium.  The plane $y,w$ is called the {\it phase plane}.  The red line is called the {\it null isocline} of $y$,
and the blue line is the null isocline of the variable $w$.  For the set of parameters we chose, we have two equilibria.
The first, where $y=0$, and the second where neither $y$ nor $w$ vanish.  It's not completely easy to see on the plot, but
the blue line is actually a hyperbola with two sections; one of them is the prominent descending arc, but the second touches
our white triangle at one point, at the origin.  So in fact $w=y=0$ is an equilibrium point, the totally disease-free
equilibrium where neither drug sensitive nor drug resistant strains are present: all people are susceptible, $X=N$, and $x=1$.

We also have the equilibrium on the vertical axis, $y=0$ but $w>0$.  What is $w$ there?  If $y=0$ and $w>0$, then
$R_{WW}(1-w)-1$.  This gives us $w=1-1/R_{WW}$.  In this case, since $R_{WW}=2$, so this happens at $w=1/2$.  Biologically,
you just have drug resistance only.  Since we assumed it could not go back to drug sensitive, if that's all you have, that's
all you get.  This is a resistance-only equilibrium.

And there's one more $\ldots$ the equilibrium out in the field, with $w>0$ and $y>0$.  Can we find it?  
\[
(1-w-1/R_{YY})\big(R_{WW}g w - (1-g)r\big)  = gw\big(R_{WW}(1-w)-1\big)
\]
This is kind of tedious, but let's do it.
\[
(1-1/R_{YY}-w)\big(R_{WW}g w - (1-g)r\big)  = gw\big(R_{WW}-1-R_{WW}w \big)
\]
Let's simplify this to $a=1-1/R_{YY}$, $e=(1-g)r$, and $f=R_{ww}-1$.
\[
(a-w)\big(R_{WW}g w - e\big)  = gw(f-R_{WW}w)
\]
\[
a R_{WW} g w - a e - R_{WW} g w^2 + ew = gwf - gw^2 R_{WW} 
\]
Luckily, the quadratic term cancels off both sides.
\[
a R_{WW} g w - a e + ew = gwf 
\]
\[
a R_{WW} g w + ew - gf w =  a e
\]
\[
w =  \frac{a e}{a R_{WW} g + e - gf} = \frac{(1-g)r\left(1-\frac{1}{R_{YY}}\right)}{g R_{WW}\left(1-\frac{1}{R_{YY}}\right) + (1-g)r - g(R_{WW}-1)} .
\]
 
\vfill
\end{document}


